### ISSUE TITLE
Provide Testcontainers modules

### ISSUE THREAD

**Issue by eddumelendez** [qdrant/java-client#21]
Hi, there is community interest about Qdrant module for [Testcontainers Java](https://github.com/testcontainers/testcontainers-java/issues/7503) and [.NET](https://github.com/testcontainers/testcontainers-dotnet/issues/992). I just found Testcontainers is being used to test the client libraries for [Java](https://github.com/qdrant/java-client/blob/776b909d06a263492cdb8c1bbfe4ea7b8499ab18/src/test/java/io/qdrant/client/container/QdrantContainer.java) and [.Net](https://github.com/qdrant/qdrant-dotnet/blob/22e5a89c0675da8900c09c9bd82daca49525aea5/tests/Qdrant.Client.Tests/QdrantFixture.cs). It would be nice to create a separate project so the community can use it as well. Nowadays, Testcontainers offers the [Module Catalog](https://testcontainers.com/modules/) for discoverability.

**Comment by eddumelendez** [comment]
I was creating a [module](https://github.com/testcontainers/testcontainers-java/pull/8353) when I noticed this. If you are interested I can donate the project to the org.

**Comment by Anush008** [comment]
Hi @eddumelendez. Thanks for the great contribution.
