### ISSUE TITLE
Cannot access com.google.protobuf.GeneratedMessageV3

### ISSUE THREAD

**Issue by Begin-Studio-LLC** [qdrant/java-client#23]
Getting the following error. 

Cannot access com.google.protobuf.GeneratedMessageV3

<dependency>
			<groupId>io.qdrant</groupId>
			<artifactId>client</artifactId>
			<version>1.7.1</version>
		</dependency>

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.0-SNAPSHOT</version>
		<relativePath/> 
	</parent>

**Comment by Anush008** [comment]
Try adding the following dependencies.
```xml
<dependencies>
    <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-protobuf</artifactId>
        <version>1.59.0</version>
    </dependency>
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>32.0.0-jre</version>
    </dependency>
    <dependency>
        <groupId>io.qdrant</groupId>
        <artifactId>client</artifactId>
        <version>1.7.1</version>
    </dependency>
</dependencies>
```

**Comment by Begin-Studio-LLC** [comment]
That worked
