### ISSUE TITLE
Allow custom strings as IDs

### ISSUE THREAD

**Issue by KlausSchaefers** [qdrant/java-client#33]
Hi, 

it seems only UUID and Long are supported as Point IDs. I need however to bring my own Strings as ids. What is the best solution here?

Thanks

**Comment by Anush008** [comment]
Qdrant only allows +ve integers and UUIDs to be used as point IDs.
https://qdrant.tech/documentation/concepts/points/#point-ids

You can try to build a deterministic UUID-V5 based on your custom ID.

**Comment by KlausSchaefers** [comment]
This could work. Why is this not included in the SDK?
