### ISSUE TITLE
create collection fail when use java-client

### ISSUE THREAD

**Issue by Emirateyang** [qdrant/java-client#39]
Using the Qdrant Cloud Free tier

my code is ：
`
  client.createCollectionAsync("MyCollecton", Collections.VectorParams.newBuilder() .setDistance(Collections.Distance.Cosine).setSize(1536).build()).get();
`
                            
and the following exception was thrown after execution.

------------------------------------------------------------------------------------
io.qdrant.client.QdrantClient            : Create collection operation failed

io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,date=Mon, 13 May 2024 10:30:18 GMT,content-length=19)
DATA-----------------------------
404 page not found

	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 common frames omitted
--------------------------------------------------------------------------------------

Is there something i missed?

Maven
io.grpc     1.59.1
io.qdrant   1.9.0
com.google.protobuf  3.24.0
guava      33.2.0-jre

**Comment by Anush008** [comment]
Hey @Emirateyang.
Can you confirm your Qdrant server version?

**Comment by Emirateyang** [comment]
Qdrant v1.9.2 is written in the bottom left corner of the dashboard. Is this a server version?

BTW，I can create collection by running curl from the command line. But i just want to use the java client in my case

**Comment by Anush008** [comment]
> Qdrant v1.9.2 is written in the bottom left corner of the dashboard. Is this a server version?
Yes.

Could you share how you're instantiating `QdrantClient`?
Since we have tests to create collections running fine on 1.9.2.

**Comment by Emirateyang** [comment]
![Dingtalk_20240513192028](https://github.com/qdrant/java-client/assets/5934358/1beb032b-cfde-4a52-a519-bf1cbc38c95e)
but my cloud server‘s port is 6333

**Comment by Anush008** [comment]
Qdrant offers [2 interfaces](https://qdrant.tech/documentation/interfaces/#api-reference).
REST on 6333.
gRPC on 6334.

The Java client uses the gRPC interface.

**Comment by Anush008** [comment]
Also this page https://github.com/qdrant/java-client/issues/39#issuecomment-2107314807, will feature the other SDK snippets soon.

**Comment by Emirateyang** [comment]
<img width="588" alt="3E1F14B9-230B-4530-94A0-992F026B0D02" src="https://github.com/qdrant/java-client/assets/5934358/c86363c5-9da7-4af3-8346-659e3c03fc93">
Same error when i change the port to 6334

**Comment by Anush008** [comment]
Here's an example to authenticate with Qdrant cloud.

https://qdrant.tech/documentation/cloud/authentication/#authenticate-via-sdk

**Comment by Emirateyang** [comment]
it works. It's my bad. I missed the documentation.
I greatly appreciate your patient guidance.

**Comment by Anush008** [comment]
Awesome.

FYI, you can take a look at https://qdrant.tech/documentation/concepts/

All sections have code examples using the official SDKs.
