### ISSUE TITLE
Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS 

### ISSUE THREAD

**Issue by duhaifeng** [qdrant/java-client#41]
Hi. I run my qdrant service  by docker and without ssl. when operate with java client it throws NotSslRecordException exception but python client is ok. How can I use java client without ssl? (because my product service did not use ssl)

--------------------------this java code does not work-----------------------------
@Test
    public void testCreateCollection() {
        try {
            QdrantClient client = new QdrantClient(QdrantGrpcClient.newBuilder("localhost").build());
            Collections.CollectionOperationResponse response = client.createCollectionAsync("my_collection",
                    Collections.VectorParams.newBuilder()
                            .setDistance(Collections.Distance.Cosine)
                            .setSize(4)
                            .build()).get();
        } catch (Exception e) {
            //here catch io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS 
            e.printStackTrace();
        }
    }

--------------------------this python code works-----------------------------
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams
 
client = QdrantClient(host="127.0.0.1", port=6333, grpc_port=6334, prefer_grpc=False)
client.create_collection(
    collection_name="test_collection1",
    vectors_config=VectorParams(size=4, distance=Distance.DOT),
)

**Comment by Anush008** [comment]
Hi @duhaifeng.
Please try using
```
QdrantClient client = new QdrantClient(
    QdrantGrpcClient.newBuilder("localhost", 6334, false).build());
 ```
  instead of
 ```
 QdrantGrpcClient.newBuilder("localhost")
 ```
 Since it defaults TLS to true.
