### ISSUE TITLE
Need update for grpc-1.63 to resolve conflicts with other packages

### ISSUE THREAD

**Issue by mamsterla** [qdrant/java-client#47]
Need to get a version with support for io.grpc-1.63 or newer - there are a number of issue with using the older versions of grpc with other packages that require grpc - this is creating a library management headache.  It would be great to get a version that uses the newer libs with the new signatures.

**Comment by Anush008** [comment]
Hey @mamsterla. Sure, updates are due.
Could you share some issues you ran into?

**Comment by mamsterla** [comment]
Sure.  I was trying to use the java client in conjunction with another package (Orkes conductor).  Both depended on GRPC and had different enough versions that signatures of the methods did not work - conductor required 1.63 and java-client required 1.59 which led to run time errors with netty-shaded.  I can check the exact errors, but a simple rebuild seemed to work.  I am using a snapshot based on no changes other than bumping the dependency.
