### ISSUE TITLE
How to connect to QDrant cluster

### ISSUE THREAD

**Issue by hgaong** [qdrant/java-client#51]
How to connect to QDrant cluster，How to do automatic routing for sharding

**Comment by russcam** [comment]
The README has a few [examples for how to connect](https://github.com/qdrant/java-client?tab=readme-ov-file#creating-a-client).

> How to do automatic routing for sharding

You don't need to do anything; [The cluster automatically routes requests to the correct node(s)](https://qdrant.tech/documentation/guides/distributed_deployment/#sharding).
