### ISSUE TITLE
Filtering results by score

### ISSUE THREAD

**Issue by sven42** [qdrant/java-client#56]
As described in the docs (https://qdrant.tech/documentation/concepts/search/#filtering-results-by-score) I would like to filter results by score.

I cannot find any filters for score in the Java-Client.
- If I overlooked something: can you provide an example on how to use it?
- If it is missing: could you please add this feature

Thanks in advance and best regards,
  Sven

**Comment by Anush008** [comment]
Hi @sven42.
It is used like so.

```java
client
    .queryAsync(
        QueryPoints.newBuilder()
            .setCollectionName(testName)
            .setQuery(nearest(10.5f, 11.5f))
            .setScoreThreshold(0.55f)
            .build())
    .get();
```

**Comment by sven42** [comment]
Hi @Anush008,

thank you very much for your fast support.
