### ISSUE TITLE
IllegalArgumentException: Invalid schemaType: 'Uuid'

### ISSUE THREAD

**Issue by canleon** [qdrant/java-client#57]
Hi there,

I have noticed that the shorthand function for [creating a payload index asynchronously](https://github.com/qdrant/java-client/blob/master/src/main/java/io/qdrant/client/QdrantClient.java#L2126) is missing a case statement. Therefore, I get an IllegalArgumentException when I try to create an index with the payload schema type UUID.

```
java.lang.IllegalArgumentException: Invalid schemaType: 'Uuid'
	at io.qdrant.client.QdrantClient.createPayloadIndexAsync(QdrantClient.java:2163)
```

I can confirm that manually creating the builder creates the index as intended.

Regards,
canleon

**Comment by Anush008** [comment]
Hey @canleon.
Thanks for pointing out. Will update the helper.
